name: on-push-main
on:
  push:
    branches:
      - main
jobs:
  preview:
    name: apply-change-to-ap-southeast-1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-region: ap-southeast-1
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Replace configuration for rds
        uses: datamonsters/replace-action@v2
        with:
          files: '09-rds/Pulumi.rds-dev.yaml'
          replacements: '$DEV_AURORA_USERNAME=${{ secrets.DEV_AURORA_USERNAME }},$DEV_AURORA_PASSWORD=${{ secrets.DEV_AURORA_PASSWORD }}'

      - name: Install Pulumi CLI
        uses: pulumi/setup-pulumi@v2

      - name: List pulumi plugin
        run: pulumi plugin ls

      - name: Install pulumi plugin EKS
        run: pulumi plugin install resource eks 0.30.0

      - name: Install pulumi plugin AWS
        run: pulumi plugin install resource aws v4.8.0

      - name: List pulumi plugin
        run: pulumi plugin ls

      - name: Install dependencies
        run: npm install

      - name: Run TSC compiler to check typescript
        run: npm run check-typescript

      - name: run lint
        run: npm run lint

      - name: run test
        run: npm run test

      - name: Up network dev
        uses: pulumi/actions@v3
        with:
          command: up
          stack-name: med4all/network-dev
          refresh: true
          work-dir: 01-network
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

      - name: Up network prod
        uses: pulumi/actions@v3
        with:
          command: up
          stack-name: med4all/network
          refresh: true
          work-dir: 01-network
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

      - name: Up EKS
        uses: pulumi/actions@v3
        with:
          command: up
          stack-name: med4all/eks-dev
          refresh: true
          work-dir: 02-eks
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

      - name: Up NLB
        uses: pulumi/actions@v3
        with:
          command: up
          stack-name: med4all/nlb-dev
          work-dir: 03-nlb
          refresh: true
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

      - name: Up NLB local
        uses: pulumi/actions@v3
        with:
          command: up
          stack-name: med4all/nlb-local-dev
          work-dir: 04-nlb-local
          refresh: true
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

      - name: Up Route53
        uses: pulumi/actions@v3
        with:
          command: up
          stack-name: med4all/route53-dev
          work-dir: 05-route53
          refresh: true
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

      - name: Up API Gateway
        uses: pulumi/actions@v3
        with:
          command: up
          stack-name: med4all/apigateway-dev
          work-dir: 06-apigateway
          refresh: true
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

      - name: Up MSK
        uses: pulumi/actions@v3
        with:
          command: up
          stack-name: med4all/msk-dev
          work-dir: 07-msk
          refresh: true
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

      - name: Up Elasticsearch
        uses: pulumi/actions@v3
        with:
          command: up
          stack-name: med4all/elasticsearch-dev
          work-dir: 08-elasticsearch
          refresh: true
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

      - name: Up RDS
        uses: pulumi/actions@v3
        with:
          command: up
          stack-name: med4all/rds-dev
          work-dir: 09-rds
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

      - name: Up s3
        uses: pulumi/actions@v3
        with:
          command: up
          stack-name: med4all/s3-dev
          work-dir: 11-s3
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

      - name: Up Private Host Zone
        uses: pulumi/actions@v3
        with:
          command: up
          stack-name: med4all/privateHostZone-dev
          work-dir: 12-privateHostZone
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
